### ISSUE TITLE
Digest authentication?

### ISSUE THREAD

**Issue by logicalshrapnel** [steineey/node-red-contrib-axios#1]
I'm struggling to make a PATCH request from node-red as the basic http-request node does not support it. I came across you package which does, but it seems it only support basic authentication? Have I missed something, or is there a chance digest authentication could be added?

**Comment by csteinba** [comment]
Hi logicalshrapnel,
sry digest authentication is not yet supported by this node. This node is a pure adaptation of [Axios](https://github.com/axios/axios) and unfortunately Axios does not currently offer the possibility for digest authentication.
