### ISSUE TITLE
Support for path variables

### ISSUE THREAD

**Issue by ImfMaciejKolkowski** [steineey/node-red-contrib-axios#4]
Hello,
thank you for your work on plugin. There is any support for  dynamic setting path variables on endpoint? Like "example.com/{id}" or something like that?

**Comment by ImfMaciejKolkowski** [comment]
I am talking about the "axios" block.

**Comment by csteinba** [comment]
You can overwrite the url with `msg.url` here you can set path variable dynamically in your flow.
Your endpoint base url would be `https://example.com/` and your flow message needs a propery `msg.url` with the id value.
